version: '3.8'

# Development override - use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
services:
  n8n-tools-api:
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount source code for hot reloading in development
      - ./app:/app/app:ro
      - ./config:/app/config:ro
      - dev-temp:/tmp/n8n-tools-api
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # Less restrictive resource limits for development
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  dev-temp:
    driver: local
