# Kubernetes Deployment Manifests

apiVersion: v1
kind: Namespace
metadata:
  name: n8n-tools-production
  labels:
    app: n8n-tools-api
    environment: production

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-tools-config
  namespace: n8n-tools-production
data:
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  MAX_FILE_SIZE_MB: "50"
  TEMP_DIR: "/tmp/n8n-tools"
  CLEANUP_AFTER_HOURS: "1"
  HEALTH_CHECK_TIMEOUT: "30"

---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-tools-secrets
  namespace: n8n-tools-production
type: Opaque
stringData:
  SECRET_KEY: "your-secret-key-here-32-chars-min"
  CORS_ORIGINS: "https://your-n8n-domain.com,https://app.n8n.io"
  AI_PDF_MISTRAL_API_KEY: "your-mistral-api-key-here"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-tools-api
  namespace: n8n-tools-production
  labels:
    app: n8n-tools-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: n8n-tools-api
  template:
    metadata:
      labels:
        app: n8n-tools-api
        version: v1
    spec:
      containers:
      - name: api
        image: n8n-tools-api:latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: n8n-tools-config
        - secretRef:
            name: n8n-tools-secrets
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp/n8n-tools
      volumes:
      - name: temp-storage
        emptyDir:
          sizeLimit: 5Gi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: n8n-tools-api-service
  namespace: n8n-tools-production
  labels:
    app: n8n-tools-api
spec:
  selector:
    app: n8n-tools-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-tools-api-ingress
  namespace: n8n-tools-production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - api.your-domain.com
    secretName: n8n-tools-api-tls
  rules:
  - host: api.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-tools-api-service
            port:
              number: 80
